# Generated by Django 2.1.2 on 2018-10-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DtInfractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.IntegerField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fine', models.IntegerField(blank=True, null=True)),
                ('loc', models.TextField(blank=True, null=True)),
                ('datetime', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dt_infractions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SqliteStat1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbl', models.TextField(blank=True, null=True)),
                ('idx', models.TextField(blank=True, null=True)),
                ('stat', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sqlite_stat1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Streetsegmentinfraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.IntegerField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fine', models.IntegerField(blank=True, null=True)),
                ('loc', models.TextField(blank=True, null=True)),
                ('datetime', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'streetsegmentinfraction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Streetsegments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('slat', models.FloatField(blank=True, null=True)),
                ('nlat', models.FloatField(blank=True, null=True)),
                ('wlng', models.FloatField(blank=True, null=True)),
                ('elng', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'streetsegments',
                'managed': False,
            },
        ),
    ]
