# Generated by Django 2.1.2 on 2018-10-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardphoto', models.ImageField(blank=True, upload_to='homepage/static/homepage/')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
