# Generated by Django 2.1.2 on 2018-10-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_portfoliopiece_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopiece',
            name='cardfooter',
            field=models.CharField(default='', max_length=150),
        ),
    ]
