# Generated by Django 2.1.2 on 2018-10-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_portfoliopiece_cardfooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopiece',
            name='cardlink',
            field=models.TextField(default=''),
        ),
    ]
