# Generated by Django 2.1.2 on 2018-10-02 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
