# Generated by Django 2.1.2 on 2018-10-03 20:30

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entry_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
