# Generated by Django 2.1.2 on 2018-10-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181003_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='coverphoto',
            field=models.ImageField(default=None, upload_to='blog/static/blog/'),
        ),
    ]
