# Generated by Django 2.1.2 on 2018-10-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_entry_coverphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='coverphoto',
            field=models.ImageField(blank=True, null=True, upload_to='blog/static/blog/'),
        ),
    ]
