# Generated by Django 2.1.2 on 2018-10-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181003_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='coverphoto',
            field=models.ImageField(blank=True, default='', upload_to='blog/static/blog/'),
        ),
    ]
