# Generated by Django 2.1.2 on 2018-10-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181003_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='coverphoto',
        ),
    ]
